---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Destroy the host_vars directory and its contents
      file: path={{ playbook_dir }}/host_vars/ state=absent

    - name: Destroy the group_vars directory and its contents
      file: path={{ playbook_dir }}/group_vars/ state=absent

    - name: Destroy hosts file in the playbook directory
      file: path={{ playbook_dir }}/hosts state=absent

    - name: Destroy extras in the playbook directory
      file: path={{ playbook_dir }}/extras state=absent

    - name: Destroy yml files in the playbook directory
      file: path={{ playbook_dir }}/{{ item }} state=absent
      with_items:
        - nuage-install.yml
        - vsd-deploy.yml
        - sec-rules.yml
        - vsd-util-postinstall.yml
        - vsd-stat-postinstall.yml
        - vsd-vsc-postinstall.yml
        - vsc-profiles.yml
        - stat-predeploy.yml
        - stat-deploy.yml
        - nserver-deploy.yml
        - util-predeploy.yml
        - util-deploy.yml
        - reset-all-domains.yml
        - ovs-deploy.yml
        - ovs-reset.yml
        - license.yml
        - deploy-all.yml
