---
# build.yml: Create your host and group var files from this
- hosts: localhost
  gather_facts: no

  vars:
    ntp_server_list:
      - "{{ lab_network_prefix }}.12"
    dns_server_list:
      - "{{ lab_network_prefix }}.12"
    dns_domain: "{{ lab_domain }}"
    public_if: bond0
    nuage_license_key: "{{ lookup('file', '/home/dev/.nuage_license_key') }}"
    summary_file: "/home/dev/packet-nuagevns/.summary"
    ssh_key:
    - "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"

  pre_tasks:

    - include_vars: "cfg/{{ nuage_release }}/elastic_ip.yml"
    - include_vars: "cfg/{{ nuage_release }}/files_location.yml"
    - include_vars: cfg/{{ nuage_release }}/packet-bmetals.yml
    - include_vars: cfg/{{ nuage_release }}/nuage-core-instances.yml 
    - include_vars: cfg/{{ nuage_release }}/nuage-sdwan-instances.yml 
    - include_vars: cfg/{{ nuage_release }}/nuage-cloud-instances.yml 

  tasks:

    - name: Create directories
      file: path={{ playbook_dir }}/{{ item }}/ state=directory
      with_items:
        - host_vars
        - group_vars
        - extras

    - name: Create host_vars files for core_instances
      template: src=servers.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
      with_items: "{{ core_instances }}"

    - name: Create host_vars files for VSC's
      template: src=vsc.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
      with_items: "{{ vsc_controllers }}"

    - name: Create host_vars files for nsg_instances
      template: src=servers.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
      with_items: "{{ nsg_instances }}"
      when: nsg_instances is defined

    - name: Create host_vars files for desktops
      template: src=servers.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
      with_items: "{{ desktops }}"
      when: desktops is defined

    - name: Create host_vars files for k8s_instances
      template: src=servers.j2 backup=no dest={{ playbook_dir }}/host_vars/{{ item.hostname }}
      with_items: "{{ k8s_instances }}"
      when: k8s_instances is defined

    - name: Create hosts file
      template: src=hosts.j2 dest="{{ playbook_dir }}/hosts" backup=no

    - name: Create group_vars/all file
      template: src=group_vars.all.j2 dest="{{ playbook_dir }}/group_vars/all" backup=no

    - name: Create files in extras
      template: src={{ item }}.j2 dest="{{ playbook_dir }}/extras/{{ item }}" backup=no
      with_items:
        - vsd_script.py
      when: nsg_instances is defined

    - name: Create files in extras for k8s
      template: src={{ item }}.j2 dest="{{ playbook_dir }}/extras/{{ item }}" backup=no
      with_items:
        - k8s-hosts-inventory
      when: k8s_instances is defined

    - name: Create files in extras for openstack
      template: src={{ item }}.j2 dest="{{ playbook_dir }}/extras/{{ item }}" backup=no
      with_items:
        - openstack-hosts-inventory
      when: openstack_release is defined

    - name: Create YML files
      template: src={{ item }}.j2 dest={{ playbook_dir }}/{{ item }} backup=no
      with_items:
        - ovs-deploy.yml
        - ovs-reset.yml
        - license.yml
        - webvirtmgr-deploy.yml
        - deploy-all.yml
        - reset-all-domains.yml
        - nuage-install.yml
        - util-predeploy.yml
        - util-deploy.yml
        - nserver-deploy.yml
        - stat-predeploy.yml
        - stat-deploy.yml
        - vsd-deploy.yml
        - vsd-postinstall.yml
        - vsc-profiles.yml


