---
- hosts: localhost
  gather_facts: no
  remote_user: root

  vars:
    packet_token: "{{ lookup('file', '/home/dev/.packet_token') }}"
    project_id: "{{ lookup('file', '/home/dev/.packet_project_id') }}"
    dns_domain: "{{ lab_domain }}"

  pre_tasks:

    - name: Read instances settings from file
      include_vars: cfg/{{ nuage_release }}/elastic_ip.yml
      include_vars: cfg/{{ nuage_release }}/packet-bmetals.yml

  tasks:

    - name: Are you sure?
      pause: prompt='This operation will destroy host_vars and bare metals! Press return to continue. Press Ctrl+c and then "a" to abort'

    - name: Removing a ssh key nuage-vns-inabox in packet.net
      packet_sshkey:
        label: "sdnlab-{{ project_id | regex_replace('^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-([0-9a-f]*)$', '\\1') }}"
        key: "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
        state: absent
        auth_token: "{{ packet_token }}"

    - name: Removing a Bare Metal server
      packet_device:
        project_id: "{{ project_id }}"
        hostnames: "{{ item.device_name }}"
        plan: "{{ item.bmetal_plan }}"
        facility: "{{ item.facility }}"
        operating_system: "{{ item.osystem }}"
        state: absent
        auth_token: "{{ packet_token }}"
      with_items: "{{ bmetals }}"


