- name: install pip in VSD
  yum: name={{ item }} state=present
  with_items:
   - python-pip
  when: hostvars[groups['util'][0]].inventory_hostname is defined
  remote_user: root

- name: install pexpect at VSD
  pip:
    name: pexpect
  when: hostvars[groups['util'][0]].inventory_hostname is defined
  remote_user: root

- name: "Waiting VSC until 3min for server to come back"
  wait_for:
    port: 22 
    host: "{{ item.vsc_host }}"
    search_regex: OpenSSH
    delay: 15
    timeout: 180
  remote_user: root
  with_items: "{{ vsc_list }}"
  ignore_errors: yes

- name: "Add VSC to VSD known_hosts list"
  shell: "ssh-keyscan -t rsa {{ item.vsc_host  }} | sed -e 's/#.*$//' | sed -e '/^$/d' > /root/.ssh/known_hosts"
  when: hostvars[groups['util'][0]].inventory_hostname is defined
  with_items: "{{ vsc_list }}"
  remote_user: root

- name: "copying certificates to VSC"
  expect:
    command: "/opt/vsd/ejbca/deploy/certMgmt.sh -a generate -u {{ item.vsc_cert_name }} -c {{ item.vsc_cert_name }} -d {{ item.vsc_fqdn }}  -f pem -t server -o csp -s admin@{{ item.vsc_host }}:/"
    responses:
      (?i)password: "{{ item.vsc_passwd }}"
  remote_user: root
  with_items: "{{ vsc_list }}"
  when: hostvars[groups['util'][0]].inventory_hostname is defined

