---
- name: Applying forwardig
  command: "/sbin/sysctl -w net.ipv4.ip_forward=1"

- name: Create bridges at ovs
  openvswitch_bridge:
    bridge: "{{ item.bridge }}"
    state: present
  with_items: "{{ br_connect }}"

- name: creating gateways ports at bridges
  openvswitch_port:
    bridge: "{{ item.bridge }}"
    port: "{{ item.bridge }}-gw"
    state: present
    set: "Interface {{ item.bridge }}-gw type=internal"
  when: item.gateway is defined
  with_items: "{{ br_connect }}"

- name: setting ip address for gateway ports
  shell: ifconfig {{ item.bridge }}-gw {{ item.gateway }}/{{ item.prefix }} up
  when: item.gateway is defined
  with_items: "{{ br_connect }}"

