---

- include: 1_ovs_install.yml
  when: br_connect is defined 

- include: 2_ovs_configure.yml
  when: br_connect is defined 

- include: 3_creating_ovs_ports.yml
  when: br_connect is defined 

- include: 4_applying_snat.yml
  when: br_connect is defined 

